title: Napkin
email: eyeversuseye@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Friends help friends, thats what they do.
baseurl: ""
url: "http://yratof.github.io/napkin/"
twitter_username: yratof
github_username:  yratof

# Build settings
markdown: kramdown
