title: Napkin
email: eyeversuseye@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Friends help friends, thats what they do.
baseurl: "/napkin/"
url: "http://yratof.github.io"
twitter_username: yratof
github_username:  yratof

# Build settings
markdown: kramdown
